;;; Automatically generated by ‘recentf’ on Tue Jan 23 20:11:07 2024.

(setq recentf-list
      '(
        "~/*message*-20240123-201035"
        "~/Hugo/Sites/golog/content/posts/Rust简明指南&Struct.md"
        "~/Bugfixer/rust/hello_match/src/main.rs"
        "~/Notes/emacs-notes/org/arch.org"
        "~/Bugfixer/rust/hello_world/src/main.rs"
        "~/.config/fish/config.fish"
        "~/.ssh/id_rsa.pub"
        "~/.config/nvim/lua/plugins/lspconfig.lua"
        "~/.emacs.d/emacs-config.org"
        "~/.config/nvim/init.lua"
        "~/Bugfixer/rust/rust_trait4/src/main.rs"
        "/usr/share/emacs/29.1/etc/AUTHORS"
        "~/Notes/emacs-notes/org/hello_rust.org"
        "~/.config/wezterm/wezterm.lua"
        "~/Bugfixer/rust/rust_trait3/src/main.rs"
        "~/Bugfixer/rust/rust_trait2/src/main.rs"
        "~/Bugfixer/rust/rust_trait/src/main.rs"
        "~/Bugfixer/rust/rust_hashmap/src/main.rs"
        "~/.config/rofi/config.rasi"
        "~/Bugfixer/rust/rust_err/src/main.rs"
        "~/Bugfixer/rust/rust_err/hello.txt"
        "~/Bugfixer/rust/rust_string/src/main.rs"
        "~/Bugfixer/rust/rust_vector/src/main.rs"
        "~/Bugfixer/rust/rust_option/src/main.rs"
        "~/Bugfixer/rust/rust_enum/src/main.rs"
        "~/Notes/emacs-notes/org/20231201T104653--archlinux__reading.org"
        "~/Bugfixer/rust/rust_struct2/src/main.rs"
        "~/Bugfixer/rust/rust_struct/src/main.rs"
        "~/Notes/rust/vx_notebook/vx_notebook.json"
        "~/Notes/rust/vx.json"
        "~/.emacs.d/helloemacs.js"
        ))

(setq recentf-filter-changer-current 'nil)


;; Local Variables:
;; coding: utf-8-emacs
;; End:
