;;; Automatically generated by ‘recentf’ on Tue Feb 13 22:48:42 2024.

(setq recentf-list
      '(
        "~/Hugo/Sites/blog/content/posts/hello.md"
        "~/Hugo/Sites/blog/content/posts/hhhh.org"
        "~/Hugo/Sites/blog/content/posts/test.md"
        "~/Hugo/Sites/blog/content/posts/hello.org"
        "~/Hugo/Sites/blog/content/posts/emacs配置easy-hugo插件.org"
        "~/.emacs.d/emacs-config.org"
        "~/Hugo/Sites/blog/content/posts/hello-w.org"
        "~/Hugo/Sites/blog/hugo.toml"
        "~/Hugo/Sites/blog/content/posts/hello_world.md"
        "~/.emacs.d/init.el"
        "~/Bugfixer/rust/hello_struct/src/main.rs"
        "~/Bugfixer/rust/rust_T/src/main.rs"
        "~/Bugfixer/rust/hello_match/src/main.rs"
        "~/Notes/emacs-notes/org/arch.org"
        "~/.config/fish/config.fish"
        "~/.ssh/id_rsa.pub"
        "~/.config/nvim/init.lua"
        "~/Notes/emacs-notes/org/hello_rust.org"
        "~/.config/wezterm/wezterm.lua"
        "~/.config/rofi/config.rasi"
        ))

(setq recentf-filter-changer-current 'nil)


;; Local Variables:
;; coding: utf-8-emacs
;; End:
