;;; Automatically generated by ‘recentf’ on Sun Feb 18 21:04:32 2024.

(setq recentf-list
      '(
        "~/Bugfixer/rust/hello_struct/src/main.rs"
        "~/Hugo/Sites/guolisen.eu.org/content/post/hello.org"
        "~/.emacs.d/emacs-config.org"
        "~/Hugo/Sites/blog/content/posts/Emacs配置easy-hugo plugin.org"
        "~/Hugo/Sites/blog/content/posts/Hugo添加自定义域名，开启SSL证书.md"
        "~/Hugo/Sites/blog/content/posts/emacs配置easy-hugo插件.org"
        "~/Hugo/Sites/blog/content/posts/hello.org"
        "/usr/share/emacs/29.2/etc/NEWS"
        "~/Hugo/Sites/blog/content/posts/hello_world.org"
        "~/Hugo/Sites/blog/content/posts/hello.md"
        "~/Hugo/Sites/blog/content/posts/hhhh.org"
        "~/Hugo/Sites/blog/content/posts/test.md"
        "~/Hugo/Sites/blog/content/posts/hello-w.org"
        "~/Hugo/Sites/blog/hugo.toml"
        "~/Hugo/Sites/blog/content/posts/hello_world.md"
        "~/.emacs.d/init.el"
        "~/Bugfixer/rust/rust_T/src/main.rs"
        "~/Bugfixer/rust/hello_match/src/main.rs"
        "~/Notes/emacs-notes/org/arch.org"
        "~/.config/fish/config.fish"
        "~/.ssh/id_rsa.pub"
        "~/.config/nvim/init.lua"
        "~/Notes/emacs-notes/org/hello_rust.org"
        "~/.config/wezterm/wezterm.lua"
        "~/.config/rofi/config.rasi"
        ))

(setq recentf-filter-changer-current 'nil)


;; Local Variables:
;; coding: utf-8-emacs
;; End:
